# Configuration Alertmanager pour Ghost Cyber Universe
# Gestion des alertes de sécurité

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@ghost-cyber-universe.com'
  smtp_auth_username: 'alerts@ghost-cyber-universe.com'
  smtp_auth_password: '${ALERTMANAGER_SMTP_PASSWORD}'

# Configuration des routes d'alerte
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'
  - match:
      alertname: 'SecurityViolation'
    receiver: 'security-team'
  - match:
      alertname: 'VulnerabilityDetected'
    receiver: 'security-team'

# Configuration des récepteurs
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'

- name: 'critical-alerts'
  email_configs:
  - to: 'security-team@ghost-cyber-universe.com'
    subject: 'CRITICAL ALERT: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      {{ end }}
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#security-alerts'
    title: 'Critical Security Alert'
    text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

- name: 'warning-alerts'
  email_configs:
  - to: 'devops-team@ghost-cyber-universe.com'
    subject: '⚠️ WARNING: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      {{ end }}

- name: 'security-team'
  email_configs:
  - to: 'security-team@ghost-cyber-universe.com'
    subject: 'SECURITY ALERT: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Time: {{ .StartsAt }}
      {{ end }}
  slack_configs:
  - api_url: '${SLACK_WEBHOOK_URL}'
    channel: '#security-critical'
    title: 'Security Alert'
    text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
  pagerduty_configs:
  - routing_key: '${PAGERDUTY_ROUTING_KEY}'
    description: '{{ .GroupLabels.alertname }}'
    details:
      summary: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
      severity: '{{ range .Alerts }}{{ .Labels.severity }}{{ end }}'

# Configuration des inhibitions
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']
