# Configuration du projet Assistant RAG Sécurisé - PME Mali

project:
  name: "rag-assistant-secure"
  version: "1.0.0"
  description: "Assistant RAG sécurisé avec toutes les fonctionnalités de sécurité"
  author: "PME Mali Security Team"
  license: "MIT"

# Configuration de l'application
application:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  reload: false
  log_level: "INFO"
  
# Configuration de la base de données
database:
  type: "sqlite"
  url: "sqlite:///./rag_assistant.db"
  echo: false
  pool_size: 5
  max_overflow: 10

# Configuration Redis
redis:
  enabled: true
  url: "redis://localhost:6379"
  db: 0
  password: null
  max_connections: 10

# Configuration des modèles IA
models:
  embedding:
    name: "sentence-transformers/all-MiniLM-L6-v2"
    max_length: 512
    batch_size: 32
  
  toxicity:
    name: "unitary/toxic-bert"
    threshold: 0.7
  
  hate_speech:
    name: "facebook/roberta-hate-speech-dynabench-r4-target"
    threshold: 0.8
  
  llm:
    provider: "openai"
    model: "gpt-3.5-turbo"
    temperature: 0.1
    max_tokens: 500

# Configuration de sécurité
security:
  # Filtrage PII
  pii:
    entities:
      - "PERSON"
      - "EMAIL_ADDRESS"
      - "PHONE_NUMBER"
      - "CREDIT_CARD"
      - "IBAN_CODE"
      - "IP_ADDRESS"
      - "LOCATION"
      - "DATE_TIME"
      - "US_SSN"
      - "US_PASSPORT"
      - "US_DRIVER_LICENSE"
      - "MEDICAL_LICENSE"
      - "NRP"
    auto_anonymize: true
    log_access: true
    require_consent: true
  
  # Modération de contenu
  content_moderation:
    toxicity_threshold: 0.7
    hate_speech_threshold: 0.8
    violence_threshold: 0.6
    sexual_content_threshold: 0.7
  
  # Détection d'injection
  injection_detection:
    prompt_injection_threshold: 0.8
    jailbreak_threshold: 0.9
    max_prompt_length: 4000
    suspicious_patterns:
      - "ignore\\s+previous\\s+instructions"
      - "forget\\s+everything"
      - "you\\s+are\\s+now\\s+a\\s+different"
      - "pretend\\s+to\\s+be"
      - "act\\s+as\\s+if"
      - "roleplay\\s+as"
  
  # Détection de secrets
  secrets_detection:
    patterns:
      - "api[_-]?key\\s*[:=]\\s*['\"]?[a-zA-Z0-9]{20,}['\"]?"
      - "password\\s*[:=]\\s*['\"]?[^\\s]{8,}['\"]?"
      - "secret\\s*[:=]\\s*['\"]?[a-zA-Z0-9]{16,}['\"]?"
      - "token\\s*[:=]\\s*['\"]?[a-zA-Z0-9]{20,}['\"]?"
      - "-----BEGIN\\s+(?:RSA\\s+)?PRIVATE\\s+KEY-----"
    confidence_threshold: 0.8
  
  # Sécurité des embeddings
  embedding_security:
    algorithm: "HMAC-SHA256"
    verify_integrity: true
    cache_signed_embeddings: true
  
  # Détection adversarial
  adversarial_detection:
    perplexity_threshold: 2.0
    toxicity_threshold: 0.7
    leakage_indicators:
      - "internal"
      - "confidential"
      - "secret"
      - "private"
      - "proprietary"
      - "restricted"
      - "classified"
    quarantine_threshold: 0.8
  
  # Chaîne d'approvisionnement
  supply_chain:
    verify_model_hashes: true
    check_sbom: true
    sandbox_execution: true
    network_policies:
      allow_outbound: false
      allowed_domains:
        - "api.openai.com"
        - "api.anthropic.com"
  
  # Gouvernance
  governance:
    risk_categories:
      - "prompt_injection"
      - "jailbreak"
      - "pii_leakage"
      - "secrets_exposure"
      - "toxic_content"
      - "adversarial_attack"
    severity_levels:
      - "low"
      - "medium"
      - "high"
      - "critical"
    mttd_target: 300  # 5 minutes
    mttr_target: 1800  # 30 minutes

# Configuration RAG
rag:
  chunk_size: 1000
  chunk_overlap: 200
  top_k: 3
  similarity_threshold: 0.7
  max_context_length: 4000
  
  vector_store:
    type: "chroma"
    persist_directory: "./chroma_db"
    collection_name: "rag_documents"

# Configuration de monitoring
monitoring:
  enabled: true
  metrics_endpoint: "/metrics"
  health_check_interval: 30
  log_retention_days: 30
  
  prometheus:
    enabled: true
    port: 9090
    scrape_interval: 15s
  
  grafana:
    enabled: true
    port: 3000
    admin_password: "admin"

# Configuration des tests
testing:
  unit_tests: true
  integration_tests: true
  security_tests: true
  load_tests: true
  performance_tests: true
  
  load_test:
    scenarios:
      - name: "light"
        requests: 50
        concurrent_users: 5
      - name: "medium"
        requests: 200
        concurrent_users: 20
      - name: "heavy"
        requests: 1000
        concurrent_users: 50
      - name: "stress"
        requests: 5000
        concurrent_users: 100
  
  security_test:
    attack_types:
      - "prompt_injection"
      - "jailbreak"
      - "secrets_extraction"
      - "pii_extraction"
      - "toxic_content"
      - "adversarial_input"
      - "dos_attack"
      - "data_poisoning"
    
    thresholds:
      block_rate_min: 0.90
      response_time_max: 5.0
      critical_attacks_max: 0

# Configuration de déploiement
deployment:
  environment: "development"  # development, staging, production
  
  docker:
    enabled: true
    image_name: "rag-assistant"
    tag: "latest"
    build_context: "."
  
  kubernetes:
    enabled: false
    namespace: "rag-assistant"
    replicas: 3
  
  scaling:
    min_replicas: 1
    max_replicas: 10
    target_cpu: 70
    target_memory: 80

# Configuration des logs
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/rag_assistant.log"
  max_size: "10MB"
  backup_count: 5
  
  security_logs:
    enabled: true
    file: "./logs/security.log"
    level: "WARNING"
  
  audit_logs:
    enabled: true
    file: "./logs/audit.log"
    level: "INFO"

# Configuration de la documentation
documentation:
  api_docs: true
  swagger_ui: true
  redoc: true
  openapi_version: "3.0.0"
  
  security_docs:
    enabled: true
    include_threat_model: true
    include_risk_assessment: true
    include_incident_response: true

# Configuration de la conformité
compliance:
  gdpr:
    enabled: true
    data_retention_days: 30
    right_to_erasure: true
    data_portability: true
  
  iso27001:
    enabled: false
    controls:
      - "A.12.6.1"
      - "A.13.1.1"
      - "A.14.1.1"
  
  nist:
    enabled: false
    framework: "cybersecurity"
    controls:
      - "PR.AC-1"
      - "PR.DS-1"
      - "PR.IP-1"
