# Ghost Cyber Universe - Docker Compose
# Configuration pour le déploiement du générateur de clés

version: '3.8'

services:
  key-generator:
    build: .
    container_name: ghost-key-generator
    ports:
      - "8000:8000"
    environment:
      - KEY_GENERATOR_HOST=0.0.0.0
      - KEY_GENERATOR_PORT=8000
      - KEY_GENERATOR_DEBUG=False
      - KEY_GENERATOR_MAX_REQUESTS_PER_MINUTE=10
      - KEY_GENERATOR_MAX_REQUESTS_PER_HOUR=100
    volumes:
      - ./logs:/app/logs
      - ./audit:/app/audit
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ghost-network

  # Service de monitoring (optionnel)
  monitoring:
    image: prom/prometheus:latest
    container_name: ghost-monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ghost-network
    profiles:
      - monitoring

networks:
  ghost-network:
    driver: bridge

volumes:
  logs:
  audit: