# Kustomization pour l'environnement de production
# Configuration de production avec sécurité maximale

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace de base
namespace: ghost-cyber-universe-production

# Ressources de base
resources:
- ../../base

# Patches pour l'environnement de production
patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml
- ingress-patch.yaml
- rbac-patch.yaml

# ConfigMaps spécifiques à la production
configMapGenerator:
- name: ghost-cyber-universe-config
  literals:
  - NODE_ENV=production
  - LOG_LEVEL=info
  - SECURITY_MODE=maximum
  - DEBUG=false
  - TESTING=false
  - MONITORING=enabled

# Secrets spécifiques à la production (références externes)
secretGenerator:
- name: ghost-cyber-universe-secrets
  literals:
  - database-url=postgresql://prod:${DB_PASSWORD}@prod-db:5432/ghost_cyber_universe
  - jwt-secret=${JWT_SECRET}
  - api-key=${API_KEY}

# Images spécifiques à la production
images:
- name: ghcr.io/ghost-cyber-universe/ghost-cyber-universe
  newTag: v1.0.0

# Labels communs
commonLabels:
  environment: production
  security-level: maximum
  compliance: required
  monitoring: enabled

# Annotations communes
commonAnnotations:
  security.ghost-cyber-universe.com/environment: "production"
  security.ghost-cyber-universe.com/scan-required: "true"
  security.ghost-cyber-universe.com/monitoring: "enabled"
  security.ghost-cyber-universe.com/backup: "enabled"
  security.ghost-cyber-universe.com/encryption: "enabled"

# Réplicas pour la production
replicas:
- name: ghost-cyber-universe
  count: 5

# Tolérations pour la production
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: ghost-cyber-universe
  patch: |-
    - op: add
      path: /spec/template/spec/tolerations/-
      value:
        key: "security.ghost-cyber-universe.com/scan"
        operator: "Equal"
        value: "passed"
        effect: "NoSchedule"
    - op: add
      path: /spec/template/spec/tolerations/-
      value:
        key: "security.ghost-cyber-universe.com/encryption"
        operator: "Equal"
        value: "enabled"
        effect: "NoSchedule"
