# Déploiement sécurisé pour Ghost Cyber Universe
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-cyber-universe
  namespace: ghost-cyber-universe
  labels:
    app: ghost-cyber-universe
    version: v1.0.0
    security-level: high
  annotations:
    security.ghost-cyber-universe.com/scan-result: "passed"
    security.ghost-cyber-universe.com/signature: "verified"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ghost-cyber-universe
  template:
    metadata:
      labels:
        app: ghost-cyber-universe
        version: v1.0.0
        security-level: high
      annotations:
        security.ghost-cyber-universe.com/pod-security: "restricted"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      # Utilisateur non-root
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      
      # ServiceAccount sécurisé
      serviceAccountName: ghost-cyber-universe-sa
      automountServiceAccountToken: false
      
      # Conteneurs sécurisés
      containers:
      - name: ghost-cyber-universe
        image: ghcr.io/ghost-cyber-universe/ghost-cyber-universe:latest
        imagePullPolicy: Always
        
        # Sécurité du conteneur
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
            - ALL
        
        # Ports
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        
        # Variables d'environnement sécurisées
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        - name: SECURITY_MODE
          value: "strict"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ghost-cyber-universe-secrets
              key: database-url
              optional: false
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ghost-cyber-universe-secrets
              key: jwt-secret
              optional: false
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: ghost-cyber-universe-secrets
              key: api-key
              optional: false
        
        # Ressources limitées
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        
        startupProbe:
          httpGet:
            path: /startup
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30
        
        # Volumes en lecture seule
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/cache
        - name: config
          mountPath: /app/config
          readOnly: true
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
      
      # Volumes sécurisés
      volumes:
      - name: tmp
        emptyDir:
          sizeLimit: 100Mi
      - name: cache
        emptyDir:
          sizeLimit: 500Mi
      - name: config
        configMap:
          name: ghost-cyber-universe-config
      - name: secrets
        secret:
          secretName: ghost-cyber-universe-secrets
      
      # Tolérations pour la sécurité
      tolerations:
      - key: "security.ghost-cyber-universe.com/scan"
        operator: "Equal"
        value: "required"
        effect: "NoSchedule"
      
      # Affinité pour la haute disponibilité
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - ghost-cyber-universe
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: security.ghost-cyber-universe.com/scan
                operator: In
                values:
                - "passed"
      
      # Restart policy
      restartPolicy: Always
      
      # DNS policy
      dnsPolicy: ClusterFirst
      
      # Termination grace period
      terminationGracePeriodSeconds: 30
