# Namespace sécurisé pour Ghost Cyber Universe
apiVersion: v1
kind: Namespace
metadata:
  name: ghost-cyber-universe
  labels:
    name: ghost-cyber-universe
    security-level: high
    compliance: required
  annotations:
    security.ghost-cyber-universe.com/network-policy: "required"
    security.ghost-cyber-universe.com/pod-security: "restricted"
    security.ghost-cyber-universe.com/rbac: "enabled"
---
# ResourceQuota pour limiter les ressources
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ghost-cyber-universe-quota
  namespace: ghost-cyber-universe
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "4"
    services: "10"
    secrets: "20"
    configmaps: "10"
---
# LimitRange pour les limites par pod
apiVersion: v1
kind: LimitRange
metadata:
  name: ghost-cyber-universe-limits
  namespace: ghost-cyber-universe
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "2"
      memory: "2Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container
