# Patch de déploiement pour l'environnement de staging
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-cyber-universe
  namespace: ghost-cyber-universe-staging
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        security.ghost-cyber-universe.com/staging: "true"
        security.ghost-cyber-universe.com/debug: "enabled"
    spec:
      containers:
      - name: ghost-cyber-universe
        env:
        - name: NODE_ENV
          value: "staging"
        - name: LOG_LEVEL
          value: "debug"
        - name: DEBUG
          value: "true"
        - name: TESTING
          value: "true"
        - name: SECURITY_MODE
          value: "strict"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ghost-cyber-universe-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ghost-cyber-universe-secrets
              key: jwt-secret
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: ghost-cyber-universe-secrets
              key: api-key
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        # Health checks spécifiques au staging
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /startup
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 30
