# Kustomization pour l'environnement de staging
# Configuration spécifique avec sécurité renforcée

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace de base
namespace: ghost-cyber-universe-staging

# Ressources de base
resources:
- ../../base

# Patches pour l'environnement de staging
patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml
- ingress-patch.yaml

# ConfigMaps spécifiques au staging
configMapGenerator:
- name: ghost-cyber-universe-config
  literals:
  - NODE_ENV=staging
  - LOG_LEVEL=debug
  - SECURITY_MODE=strict
  - DEBUG=true
  - TESTING=true

# Secrets spécifiques au staging
secretGenerator:
- name: ghost-cyber-universe-secrets
  literals:
  - database-url=postgresql://staging:password@staging-db:5432/ghost_cyber_universe
  - jwt-secret=staging-jwt-secret-key
  - api-key=staging-api-key-12345

# Images spécifiques au staging
images:
- name: ghcr.io/ghost-cyber-universe/ghost-cyber-universe
  newTag: staging-latest

# Labels communs
commonLabels:
  environment: staging
  security-level: high
  compliance: required

# Annotations communes
commonAnnotations:
  security.ghost-cyber-universe.com/environment: "staging"
  security.ghost-cyber-universe.com/scan-required: "true"
  security.ghost-cyber-universe.com/monitoring: "enabled"

# Réplicas pour le staging
replicas:
- name: ghost-cyber-universe
  count: 2
